module.exports = {
  NODE_ENV: '"production"',
  GOOGLE_API_KEY: '"AIzaSyAxc8nUYwdPKwcidFEW3gFng2wmwx3rskc"',
  SERVER_ROOT_URL: '"https://selltix.herokuapp.com"',
  API_URL: '"https://selltix.herokuapp.com/graphql"',
  ACTION_CABLE_URL: '"wss://selltix.herokuapp.com"',
  ADMIN_API_URL: '"http://selltix.herokuapp.com/tix_admin/graphql"',
  PAYSTACK_NG_PUBLIC_KEY: '"pk_live_22da047ab4e0b41037bf214fa972839653b122fc"',
  PAYSTACK_GH_PUBLIC_KEY: '""',
  PAYSTACK_SA_PUBLIC_KEY: '""',
  FLUTTERWAVE_PUBLIC_KEY: '"FLWPUBK-cce1b4d261c174a58289206a03973ec3-X"',
  GOOGLE_ANALYTICS_ID: '"UA-61268242-2"',
  FACEBOOK_PIXEL_ID: '"232211144445039"',
  INTERCOM_ID: '"txbfrko5"',
  INTERCOM_HMAC_KEY: '"JcLnRo30xlGORRn7KYQCasGNBgKJVRhPPXBrKuTd"',
  ZOOM_CLIENT_ID: '"7oTEPGsvQdmB4txMiK1PWg"',
  ZOOM_REDIRECT_URL: '"https://tix.africa/oauth/code"',
  CUSTOM_EMAIL: '"o.umukoro@mixtafrica.com,events@tix.africa,"',
}
