version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: element-ui
    versions:
    - 2.15.0
  - dependency-name: vue-loader
    versions:
    - 16.1.2
  - dependency-name: actioncable
    versions:
    - 5.2.4
