mutation organizationVerificationRequests {
  allOrganizationVerificationRequests {
    id
    accountNumber
    accountName
    approved
    registrationDocument
    organization {
      id
      name
      description
    }
  }
}
