query membershipRequests {
	membershipRequests {
    id
    createdAt
    organization {
      id
      name
      description
    }
    setAdmin
    toEmail
    createdAt
    user {
      id
      email
      firstName
      lastName
    }
  }
}

